# Generated by Django 5.2.17 on 2026-09-05 10:45

import stations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='worker_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='journeys', to='stations.crew'),
        ),
        migrations.AddField(
            model_name='train',
            name='image',
            field=models.ImageField(null=True, upload_to=stations.models.train_image_file_path),
        ),
    ]
